const EMOJI_POR_PALABRA = {
  leche: "🥛",
  yogur: "🥛",
  yogurt: "🥛",
  queso: "🧀",
  manteca: "🧈",
  crema: "🥛",
  huevo: "🥚",
  huevos: "🥚",
  pan: "🍞",
  factura: "🥐",
  facturas: "🥐",
  medialuna: "🥐",
  medialunas: "🥐",
  papa: "🥔",
  papas: "🥔",
  tomate: "🍅",
  tomates: "🍅",
  cebolla: "🧅",
  cebollas: "🧅",
  zanahoria: "🥕",
  zanahorias: "🥕",
  palta: "🥑",
  paltas: "🥑",
  lechuga: "🥬",
  banana: "🍌",
  bananas: "🍌",
  manzana: "🍎",
  manzanas: "🍎",
  limon: "🍋",
  limón: "🍋",
  naranja: "🍊",
  ajo: "🧄",
  milanesa: "🥩",
  milanesas: "🥩",
  carne: "🥩",
  asado: "🥩",
  pollo: "🍗",
  pescado: "🐟",
  arroz: "🍚",
  fideos: "🍝",
  pasta: "🍝",
  aceite: "🧴",
  sal: "🧂",
  azucar: "🧂",
  azúcar: "🧂",
  yerba: "🧉",
  cafe: "☕",
  café: "☕",
  te: "🍵",
  té: "🍵",
  galletitas: "🍪",
  chocolate: "🍫",
  vino: "🍷",
  cerveza: "🍺",
  agua: "💧",
  gaseosa: "🥤",
  detergente: "🧴",
  lavandina: "🧴",
  suavizante: "🧴",
  jabon: "🧼",
  jabón: "🧼",
  shampoo: "🧴",
  champu: "🧴",
  papel: "🧻",
  servilletas: "🧻",
  esponja: "🧽",
  lampazo: "🧹",
  escoba: "🧹",
  pilas: "🔋",
};

export function emojiParaProducto(nombre, categoria) {
  const clave = nombre.trim().toLowerCase();
  for (const palabra of Object.keys(EMOJI_POR_PALABRA)) {
    if (clave.includes(palabra)) return EMOJI_POR_PALABRA[palabra];
  }
  return categoria?.emoji ?? "🛒";
}
